routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/post/{id}', 'WelcomeController@post')->name('post.single');
Route::get('/post/category/{category_id}', 'WelcomeController@byCategory')->name('posts.category');
Route::get('/post/user/{user_id}', 'WelcomeController@byAuthor')->name('posts.author');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/categories', 'CategoryController');
Route::resource('/posts', 'PostController');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title','image', 'body','category_id'];

    protected $appends = ['image_url'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getImageUrlAttribute()
    {
        if (!is_null($this->image)) {
            return asset("/uploads/" . $this->image);
        }

        return null;
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->diffForHumans();
    }
}

resources/views/author.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="my-4">Posts list on the <strong>{{$user->name}}</strong></h1>

            @forelse($posts as $post)
                <!-- Blog Post -->
                <div class="card mb-4">
                    @if($post->image)
                    <img class="card-img-top" src="{{$post->image_url}}" alt="Card image cap">
                    @else
                    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                    @endif
                    <div class="card-body">
                        <h2 class="card-title">{{$post->title}}</h2>
                        <p class="card-text">{!! $post->body !!}</p>
                        <a href="{{route('post.single', ['id' => $post->id])}}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                        @include('partials.footer-post')
                </div>
            @empty
                <div class="alert alert-warning">
                    Não há nenhuma postagem até o momento
                </div>
            @endforelse

        </div>

        <!-- Sidebar Widgets Column -->
        @include('partials.sidebar')

    </div>
    <!-- /.row -->
@endsection

resources/views/category.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="my-4">Posts list on the <strong>{{$category->name}}</strong></h1>

            @forelse($posts as $post)
                <!-- Blog Post -->
                <div class="card mb-4">
                    @if($post->image)
                    <img class="card-img-top" src="{{$post->image_url}}" alt="Card image cap">
                    @else
                    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                    @endif
                    <div class="card-body">
                        <h2 class="card-title">{{$post->title}}</h2>
                        <p class="card-text">{!! $post->body !!}</p>
                        <a href="{{route('post.single', ['id' => $post->id])}}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                        @include('partials.footer-post')
                </div>
            @empty
                <div class="alert alert-warning">
                    Não há nenhuma postagem até o momento
                </div>
            @endforelse

        </div>

        <!-- Sidebar Widgets Column -->
        @include('partials.sidebar')

    </div>
    <!-- /.row -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading text-center">
                    Categorias
                </div>
                <div class="panel-body">
                    <h1 class="text-center">
                        {{ $categorias_count  }}
                    </h1>
                </div>
                <div class="panel-footer text-center">
                    <a href="{{route('categories.index')}}" class="btn btn-primary">Listagem</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-warning">
                <div class="panel-heading text-center">
                    Postagens
                </div>
                <div class="panel-body">
                    <h1 class="text-center">
                        {{ $posts_count  }}
                    </h1>
                </div>
                <div class="panel-footer text-center">
                    <a href="{{route('posts.index')}}" class="btn btn-primary">Listagem</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/single.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <h1 class="mt-4">{{$post->title}}</h1>

            <!-- Author -->
            <p class="lead">
                by
                <a href="{{route('posts.author', ["user_id" => $post->user_id])}}">{{$post->user->name}}</a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Posted on {{$post->created_at}}</p>

            <hr>

            <!-- Preview Image -->
            @if($post->image)
                <img class="img-fluid rounded" src="{{$post->image_url}}" alt="Card image cap">
            @else
                <img class="img-fluid rounded" src="http://placehold.it/750x300" alt="Card image cap">
            @endif

            <hr>

            <!-- Post Content -->
            {!! $post->body !!}

            <!-- Comments Form -->
            <div class="card my-4">
                <h5 class="card-header">Leave a Comment:</h5>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>

            <!-- Single Comment -->
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>

            <!-- Comment with nested comments -->
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

                    <div class="media mt-4">
                        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                        <div class="media-body">
                            <h5 class="mt-0">Commenter Name</h5>
                            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        </div>
                    </div>

                    <div class="media mt-4">
                        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                        <div class="media-body">
                            <h5 class="mt-0">Commenter Name</h5>
                            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <!-- Sidebar Widgets Column -->
        @include('partials.sidebar')

    </div>
    <!-- /.row -->
@endsection