routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/post/{id}', 'WelcomeController@post')->name('post.single');
Route::get('/post/category/{category_id}', 'WelcomeController@byCategory')->name('posts.category');
Route::get('/post/user/{user_id}', 'WelcomeController@byAuthor')->name('posts.author');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/categories', 'CategoryController');
Route::resource('/posts', 'PostController');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title','image', 'body','category_id'];

    protected $appends = ['image_url'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getImageUrlAttribute()
    {
        if (!is_null($this->image)) {
            return asset("/uploads/" . $this->image);
        }

        return null;
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->diffForHumans();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;

class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = auth()->user()->posts()->get();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = auth()->user()->categories()->get();
        return view('posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "category_id" => "required",
            "title" => "required|min:5|max:100",
            "body" => "required|max:5000",
            "image" => "required|image|mimes:png,jpeg,jpg|max:2048"
        ]);

        $data = $this->uploadData($request);

        $request->user()->posts()->create($data);

        Session::flash('success', 'Postagem criada com sucesso');

        return redirect()->route('posts.index');

    }

    private function uploadData($request)
    {
        $data = $request->all();

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = time() . "-" . $image->getClientOriginalName();
            Image::make($image->path())->fit(750, 300)->save(public_path("uploads/") . $filename);
            $data["image"] = $filename;
        }

        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = auth()->user()->posts()->find($id);

        if (!$post) {
            Session::flash('danger', 'Postagem não encontrada');
            return redirect()->route('posts.index');
        }

        $categories = auth()->user()->categories()->get();

        return view('posts.edit', compact('post','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            "category_id" => "required",
            "title" => "required|min:5|max:100",
            "body" => "required|min:5|max:100",
        ]);

        $post = auth()->user()->posts()->find($id);

        if (!$post) {
            Session::flash('danger', 'Postagem não encontrada');
            return redirect()->route('posts.index');
        }

        $post->update($request->all());

        Session::flash('success', 'Postagem atualizada com sucesso');

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = auth()->user()->posts()->find($id);

        if (!$post) {
            Session::flash('danger', 'Postagem não encontrada');
            return redirect()->route('posts.index');
        }

        $post->delete();

        Session::flash('success', 'Postagem deletada com sucesso');

        return redirect()->route('posts.index');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                Criar postagem
                <a href="{{route('posts.index')}}" class="btn btn-warning">Voltar</a>
            </div>

            <div class="panel-body">

                @include('partials.errors')

                <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <label for="title">Categoria</label>
                        <select name="category_id" class="form-control">
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="title">Título</label>
                        <input type="text" name="title" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="title">Corpo da postagem</label>
                        <textarea name="body" id="body" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="image">Imagem</label>
                        <input type="file" name="image" id="image" class="form-control" />
                    </div>
                    <div class="form-group">
                        <div class="text-center">
                            <button class="btn btn-success" type="submit"> Salvar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar postagem: {{$post->name}}
                <a href="{{route('posts.index')}}" class="btn btn-warning">Voltar</a>
            </div>

            <div class="panel-body">

                @include('partials.errors')

                <form action="{{ route('posts.update', ['id' => $post->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <div class="form-group">
                        <label for="title">Categoria</label>
                        <select name="category_id" class="form-control">
                            @foreach($categories as $category)
                                <option value="{{$category->id}}"
                                @if($post->category_id ===  $category->id) selected @endif
                                >{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="title">Título</label>
                        <input type="text" name="title" class="form-control" value="{{$post->title}}">
                    </div>
                    <div class="form-group">
                        <label for="title">Corpo da postagem</label>
                        <textarea name="body" class="form-control">{{$post->body}}</textarea>
                    </div>
                    <div class="form-group">
                        <div class="text-center">
                            <button class="btn btn-success" type="submit"> Salvar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(Session::has('danger'))
            <div class="alert alert-danger">
                {{Session::get('danger')}}
            </div>
        @endif
        @if(Session::has('info'))
            <div class="alert alert-info">
                {{Session::get('info')}}
            </div>
        @endif
        @if(Session::has('success'))
            <div class="alert alert-success">
                {{Session::get('success')}}
            </div>
        @endif
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="{{route('posts.create')}}" class="btn btn-primary">Adicionar</a>
                <hr>
                <table class="table table-hover">
                    <thead>
                    <th>Usuário</th>
                    <th>Categoria</th>
                    <th>Título</th>
                    <th>Criado em</th>
                    <th>Editar</th>
                    <th>Deletar</th>
                    </thead>
                    <tbody>
                    @if(count($posts) > 0)
                        @foreach($posts as $post)
                            <tr>
                                <td>{{ $post->user->name }}</td>
                                <td>{{ $post->category->name }}</td>
                                <td>{{ $post->title }}</td>
                                <td>{{ $post->created_at }}</td>
                                <td>
                                    <a href="{{ route('posts.edit', ['id' => $post->id]) }}" class="btn btn-xs btn-info">
                                        Editar
                                    </a>
                                </td>
                                <td>
                                    <form method="post" action="{{route('posts.destroy', $post->id)}}" onsubmit="return confirm('Deseja realmente deletar')">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="btn btn-danger btn-xs">Deletar</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr><td>Nenhuma postagem cadastrada</td></tr>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection